apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    example.com: example
  labels:
    app: foo
  name: imenus.iface.aif.io
spec:
  group: iface.aif.io
  names:
    categories:
      - aif
      - iface-aif-io
    kind: IMenu
    listKind: IMenuList
    plural: imenus
    shortNames:
      - b
    singular: imenu
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                menu:
                  items:
                    properties:
                      applyTo:
                        items:
                          enum:
                            - ADMIN
                            - DEV
                            - TENANT
                          type: string
                        type: array
                      child:
                        items:
                          properties:
                            child:
                              items:
                                properties:
                                  icon:
                                    type: string
                                  name:
                                    type: string
                                  roles:
                                    items:
                                      type: string
                                    type: array
                                  route:
                                    type: string
                                  sort:
                                    format: int32
                                    type: integer
                                  url:
                                    type: string
                                type: object
                              type: array
                            icon:
                              type: string
                            name:
                              type: string
                            roles:
                              items:
                                type: string
                              type: array
                            route:
                              type: string
                            sort:
                              format: int32
                              type: integer
                            url:
                              type: string
                          type: object
                        type: array
                      icon:
                        type: string
                      name:
                        type: string
                      roles:
                        items:
                          type: string
                        type: array
                      route:
                        type: string
                      sort:
                        format: int32
                        type: integer
                      url:
                        type: string
                    type: object
                  type: array
                prdCode:
                  type: string
                prdName:
                  type: string
                prdVersion:
                  type: string
              type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
